In [3]:
import numpy as np
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [4]:
# to print the matrix of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# to print the no of ones
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# to print the range of 0 to n-1
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Evenly Spaced Numbers
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim) # Dimension
print(arr.shape) # Rows,column
print(arr.size) # total no of elments
print(arr.dtype) # Datatype

2
(2, 3)
6
int64


In [9]:
# type conversion float to integer type
arr=np.array([1.2,2.5,3.7])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


In [10]:
# indexing and slicing
arr = np.array([10,20,30,40])
print(arr[0])#indexing to first element
print(arr[-1])#indexing to last element

10
40


In [11]:
print(arr[1:3])
print(arr[:2])
print(arr[::2]) #step size

[20 30]
[10 20]
[10 30]


In [12]:
# indexing on 2D array
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

# slicing
print(mat[:,1]) #column 1

2
[4 5 6]
[2 5 8]


In [13]:
# copy array
a=np.array([1,2,3])
b=a.copy()
b[0]=99 # to update the element in the copied array
print(a)
print(b)

[1 2 3]
[99  2  3]


In [14]:
# array operation
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [15]:
# scaler operation direct multiplication 
print(a+10)
print(a * 2)

[11 12 13]
[2 4 6]


In [16]:
# unfus (universal function)
arr=np.array([1,2,3])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr)) #standard deviation

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
3
1
2.0
6
0.816496580927726


In [17]:
# boolean indexing
arr = np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr>25)

[30 40 50]
[False False  True  True  True]


In [18]:
# broadcasting rule
arr = np.array([1,2,3,4,5])
print(arr+10)

[11 12 13 14 15]


In [19]:
# matrix multiplication

A=np.array([[1,2],[5,6]])
B=np.array([[5,6],[1,2]])

print(np.dot(A,B))


[[ 7 10]
 [31 42]]


In [20]:
print(A.T)#transepose of a matrix

[[1 5]
 [2 6]]


In [21]:
# random module
np.random.randint(1,100,10) #first 2 parameters are range and 3 tell about the no of element
# np.random.rand(5) print the float no less then zero

array([74, 75, 25, 53, 19,  7, 39, 62,  3, 65], dtype=int32)

In [22]:
# reshape array
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
#to calculate the sum of column
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
print(np.sum (arr, axis=0)) #column
print(np.sum (arr, axis=1)) #row



[5 7 9]
[ 6 15]


In [25]:
# where in numpy
arr = np.array([10,-5,20,-3,15])
print(arr)

result = np.where(arr<0, 0, arr)
print(result)

[10 -5 20 -3 15]
[10  0 20  0 15]


In [26]:
result=np.where(arr%2 !=0, -1, arr)
print(result)

[10 -1 20 -1 -1]


In [27]:
# appling where condition in 2d array