In [1]:
# you are managing the electronics section in a store . you need to track the sales of **3 products over 4 days(monday to thursday)
# row 0: headphone
# row 1: Smartphone
# row 3:speakers

In [2]:
import numpy as np
costprice= np.array([1500,3000,5000])
print(costprice)

[1500 3000 5000]


In [3]:
# print the shape and dimension
arr=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(np.shape(arr))
print(np.ndim(arr))

(3, 4)
2


In [4]:
arr2=arr+2
print(arr2)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [5]:
# multiply the price array
print(arr*arr2)

[[120 255  80 168]
 [ 35  63  24  48]
 [  8  15   8  24]]


In [6]:
# find the square root of all sales value for a statistical curve
print(np.sqrt(arr))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [7]:
print(arr[0])

[10 15  8 12]


In [8]:
print(arr[:2])

[[10 15  8 12]
 [ 5  7  4  6]]


In [9]:
print(np.arange(12))
print(arr.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [10]:
#random module
arr3=np.random.randint(0,20,12)
print(arr3.reshape(3,4))

[[ 0  4  7  6]
 [11 10  9 15]
 [ 7 15 12  0]]


In [11]:
print(np.random.rand(5))

[0.11719256 0.48692889 0.72594007 0.36843079 0.32164345]


In [12]:
#total item sold
print(np.sum(arr))

78


In [13]:
# ---------EXERCISE NO 2-----------------
import numpy as np
marks= np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
marks

array([[78, 85, 90],
       [45, 60, 55],
       [88, 92, 95],
       [30, 40, 35],
       [65, 70, 75]])

In [14]:
print(np.shape(marks)) # shapes
print(marks.size) #size and total no of element


(5, 3)
15


In [15]:
print(marks[1]) # marks of 2 student
print(marks[:,2])# marks of 3 subject
print(marks[0:2]) # marks of stu1 and stu2

[45 60 55]
[90 55 95 35 75]
[[78 85 90]
 [45 60 55]]


In [16]:
avg1= np.sum(marks[:,0]) 
print(avg1/5) #for marks of ist sub
avg2= np.sum((marks[:,1])/5)
print(avg2)
print(np.sum((marks[:,2])/5))

61.2
69.4
70.0


In [17]:
print(np.sum((marks[0,:])/5)) # for each student
print(np.sum((marks[1,:])/5))
print(np.sum((marks[2,:])/5))

50.6
32.0
55.0


In [18]:
#pass \ fail mapping

result = np.where(marks > 50, "Pass", "Fail")

print(result)


[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


In [19]:
avg_marks = np.mean(marks, axis=1)
print(avg_marks)


[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [20]:
grades = np.where(avg_marks >= 85, "A",
         np.where(avg_marks >= 70, "B",
         np.where(avg_marks >= 50, "C", "Fail")))

print(grades)


['B' 'C' 'A' 'Fail' 'B']


In [21]:
# copy vs view
marks2= marks.copy()
print(marks2)

marks3= marks.view()
print(marks3)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [22]:
marks3[0,0]=0
print(marks) # original one
print(marks3)# view array
print(marks2)#copy array

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [23]:
# --------------------------Exercise 3
# arrayname: electricity
# shape = 4,7
# rows: hostals(H1,H2,H3,H4)
# column: Days(Mon-Sun)

In [24]:
import numpy as np
electricity = np.random.randint(120,650,size=(4,7))
electricity
# electricity.reshape(4,7)


array([[142, 281, 125, 473, 411, 440, 230],
       [304, 487, 517, 122, 302, 147, 362],
       [610, 235, 414, 513, 224, 440, 621],
       [636, 247, 311, 237, 395, 493, 382]], dtype=int32)

In [25]:
# task : to find the hostel which has avg electricity consumption
print(np.sum((electricity[0,:])/7)) 
print(np.sum((electricity[1,:])/7))
print(np.sum((electricity[2,:])/7))
print(np.sum((electricity[3,:])/7))


300.2857142857143
320.14285714285717
436.7142857142857
385.85714285714283


In [26]:

avg=print(np.sum((electricity[:,0])/7)) 
print(np.sum((electricity[:,1])/7))
print(np.sum((electricity[:,2])/7))
print(np.sum((electricity[:,3])/7))
print(np.sum((electricity[:,4])/7))
print(np.sum((electricity[:,5])/7))
print(np.sum((electricity[:,6])/7))


241.71428571428572
178.57142857142856
195.28571428571428
192.14285714285714
190.28571428571428
217.14285714285717
227.85714285714283


In [27]:
policy = np.where(electricity>550,electricity*0.2+electricity,electricity)
policy

array([[142. , 281. , 125. , 473. , 411. , 440. , 230. ],
       [304. , 487. , 517. , 122. , 302. , 147. , 362. ],
       [732. , 235. , 414. , 513. , 224. , 440. , 745.2],
       [763.2, 247. , 311. , 237. , 395. , 493. , 382. ]])

In [28]:
resh=electricity.reshape(1,28)
resh

array([[142, 281, 125, 473, 411, 440, 230, 304, 487, 517, 122, 302, 147,
        362, 610, 235, 414, 513, 224, 440, 621, 636, 247, 311, 237, 395,
        493, 382]], dtype=int32)

In [29]:
resh1=electricity.reshape(2,14)
resh1

array([[142, 281, 125, 473, 411, 440, 230, 304, 487, 517, 122, 302, 147,
        362],
       [610, 235, 414, 513, 224, 440, 621, 636, 247, 311, 237, 395, 493,
        382]], dtype=int32)

In [30]:
ref_backup = electricity  #it change the original array also   
safe_backup = electricity.copy()
electricity[0,0]=50

safe_backup

array([[142, 281, 125, 473, 411, 440, 230],
       [304, 487, 517, 122, 302, 147, 362],
       [610, 235, 414, 513, 224, 440, 621],
       [636, 247, 311, 237, 395, 493, 382]], dtype=int32)